on:
  push:
    branches:
      - master
name: buildImageforECR
jobs:
  imageBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Get Cloud Native Build
        run: wget https://github.com/buildpack/pack/releases/download/v0.5.0/pack-v0.5.0-linux.tgz

      - name: Unzip file
        run: tar xvf ./pack-v0.5.0-linux.tgz

      - name: Remove pack
        run: rm pack-v0.5.0-linux.tgz

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO_NAME }}
        run: |
          IMAGE_TAG=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          ./pack build --path . $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --builder  cloudfoundry/cnb:bionic
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
